### ISSUE TITLE
Could not pass event InventoryOpenEvent to AuxProtect v1.3

### ISSUE THREAD

**Issue by fanzth** [ks-hl/AuxProtect#25]
[31May2024 02:32:37.938] [Server thread/ERROR] [Minecraft/]: Could not pass event InventoryOpenEvent to AuxProtect v1.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1163) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactoryMixin.java:1149) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntityMixin.java:318) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftHumanEntity.openInventory(CraftHumanEntityMixin.java:303) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at com.Zrips.CMI.commands.list.ender.perform(ender.java:49) ~[CMI-9.6.9.8.jar:?]
	at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:403) ~[CMI-9.6.9.8.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:761) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandlerMixin.java:2547) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandlerMixin.java:2397) ~[?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:36) ~[?:?]
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(CChatMessagePacketMixin.java:9) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.mdd48702$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:696) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.tileentity.EnderChestTileEntity.func_145831_w()" because "this.field_70488_a" is null
	at net.minecraft.inventory.EnderChestInventory.getLocation(EnderChestInventoryMixin.java:553) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventory.getLocation(CraftInventoryMixin.java:531) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3]
	at dev.heliosares.auxprotect.spigot.listeners.InventoryListener.log(InventoryListener.java:55) ~[AuxProtect-1.3.jar:?]
	at dev.heliosares.auxprotect.spigot.listeners.InventoryListener.onInventoryOpenEvent(InventoryListener.java:33) ~[AuxProtect-1.3.jar:?]
	... 30 more
	
**### i think it happend because in my server player can use /ender to open enderchest so on close
"at net.minecraft.inventory.EnderChestInventory.getLocation" is null then error happen**

**Comment by ks-hl** [comment]
Should be harmless. Will fix in the next release.
