### ISSUE TITLE
Could not pass event PlayerItemConsumeEvent to AuxProtect v1.3

### ISSUE THREAD

**Issue by reamianv** [ks-hl/AuxProtect#26]
[12:47:14 ERROR]: Could not pass event PlayerItemConsumeEvent to AuxProtect v1.3
java.lang.NoSuchMethodError: 'org.bukkit.potion.PotionType org.bukkit.inventory.meta.PotionMeta.getBasePotionType()'
        at dev.heliosares.auxprotect.spigot.listeners.PlayerListener.onConsume(PlayerListener.java:190) ~[AuxProtect-1.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1739.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2060]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:4064) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:1864) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3924) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2562) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3904) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3057) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:305) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:780) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:376) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:611) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1615) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2060]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by reamianv** [comment]
I forgot I already Issue
